#!/usr/bin/env python3
"""Build dist/constraints.json — the machine-loadable form of the corpus.

Why a build artifact at all, when the YAML is right there:

  * Consumers should not need a YAML parser. Flightforge ships with no runtime
    dependencies and its test suite keeps the same rule, which is why it was
    scraping the corpus with a regex. A single JSON file is readable from the
    standard library of every language involved.
  * Vendoring one file is reviewable. Vendoring a directory is not.
  * An id index means a consumer pins `cfr-25.527-b2-c1-value` rather than a
    line number or a file offset.

The output is deterministic — sorted keys, no timestamps, no git SHA. That is
what lets CI assert that regenerating is a no-op, which is how a stale artifact
gets caught.

Usage:  python3 tools/build.py [--check]
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT = Path(__file__).resolve().parents[1]
CONSTRAINTS = ROOT / "constraints"
OUT = ROOT / "dist" / "constraints.json"


def _isoify(obj):
    if isinstance(obj, dict):
        return {k: _isoify(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_isoify(v) for v in obj]
    if isinstance(obj, (_dt.date, _dt.datetime)):
        return obj.isoformat()
    return obj


def build() -> dict:
    entries: list[dict] = []
    for path in sorted(CONSTRAINTS.glob("*.yaml")):
        for entry in _isoify(yaml.safe_load(path.read_text(encoding="utf-8"))):
            entry["source_file"] = path.name
            entries.append(entry)

    entries.sort(key=lambda e: e["id"])

    editions = sorted({e["source"]["edition"] for e in entries})
    by_status: dict[str, int] = {}
    for e in entries:
        st = e["verification"]["status"]
        by_status[st] = by_status.get(st, 0) + 1

    doc = {
        "$comment": (
            "Generated by tools/build.py from constraints/*.yaml. Do not edit. "
            "Correct the YAML upstream and rebuild."
        ),
        "corpus": "amphibious-aircraft-ontology",
        "schema": "schema/constraint.schema.json",
        "entry_count": len(entries),
        "editions": editions,
        "verification_summary": dict(sorted(by_status.items())),
        "entries": entries,
    }

    # Content digest over the entries alone, so it changes when and only when
    # the constraints do. Consumers can pin this to detect a silent re-vendor.
    payload = json.dumps(entries, sort_keys=True, separators=(",", ":"))
    doc["content_sha256"] = hashlib.sha256(payload.encode("utf-8")).hexdigest()

    return doc


def main() -> int:
    doc = build()
    text = json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False) + "\n"

    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"STALE — {OUT.relative_to(ROOT)} does not match the corpus")
            return 1
        print(f"OK — {OUT.relative_to(ROOT)} is current")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(ROOT)} — {doc['entry_count']} entries, "
        f"sha256 {doc['content_sha256'][:12]}, "
        f"{doc['verification_summary']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
