#!/usr/bin/env python3
"""Build dist/*.json — the machine-loadable form of the corpus.

Why a build artifact at all, when the YAML is right there:

  * Consumers should not need a YAML parser. Flightforge ships with no runtime
    dependencies and its test suite keeps the same rule, which is why it was
    scraping the corpus with a regex. AeroGit is Rust and carries no YAML
    dependency either. A single JSON file is readable from the standard
    library of every language involved.
  * Vendoring one file is reviewable. Vendoring a directory is not.
  * An id index means a consumer pins `cfr-25.527-b2-c1-value` rather than a
    line number or a file offset.

Two artifacts, not one. `constraints.json` and `parameters.json` are built the
same way and kept separate on purpose: each carries a `content_sha256` over its
own entries, so a consumer pinning one is not disturbed when the other changes.
Folding them together would make every parameter edit look like a constraint
edit to anyone watching that digest.

The output is deterministic — sorted keys, no timestamps, no git SHA. That is
what lets CI assert that regenerating is a no-op, which is how a stale artifact
gets caught.

Usage:  python3 tools/build.py [--check]
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"

# Each artifact: source directory, output file, and the schema it validates
# against. `editions` is only meaningful where entries carry a `source` block,
# which parameters do not — a design parameter has a definition, not an issue
# date.
ARTIFACTS = (
    {
        "name": "constraints",
        "src": ROOT / "constraints",
        "out": DIST / "constraints.json",
        "schema": "schema/constraint.schema.json",
        "editions": True,
    },
    {
        "name": "parameters",
        "src": ROOT / "parameters",
        "out": DIST / "parameters.json",
        "schema": "schema/parameter.schema.json",
        "editions": False,
    },
)


def _isoify(obj):
    if isinstance(obj, dict):
        return {k: _isoify(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_isoify(v) for v in obj]
    if isinstance(obj, (_dt.date, _dt.datetime)):
        return obj.isoformat()
    return obj


def build(artifact: dict) -> dict:
    entries: list[dict] = []
    for path in sorted(artifact["src"].glob("*.yaml")):
        for entry in _isoify(yaml.safe_load(path.read_text(encoding="utf-8"))):
            entry["source_file"] = path.name
            entries.append(entry)

    entries.sort(key=lambda e: e["id"])

    by_status: dict[str, int] = {}
    for e in entries:
        st = e["verification"]["status"]
        by_status[st] = by_status.get(st, 0) + 1

    doc = {
        "$comment": (
            f"Generated by tools/build.py from {artifact['name']}/*.yaml. "
            "Do not edit. Correct the YAML upstream and rebuild."
        ),
        "corpus": "amphibious-aircraft-ontology",
        "schema": artifact["schema"],
        "entry_count": len(entries),
        "verification_summary": dict(sorted(by_status.items())),
        "entries": entries,
    }
    if artifact["editions"]:
        doc["editions"] = sorted({e["source"]["edition"] for e in entries})

    # Content digest over the entries alone, so it changes when and only when
    # this artifact's own entries do. Consumers can pin it to detect a silent
    # re-vendor, and pinning one artifact is not disturbed by the other moving.
    payload = json.dumps(entries, sort_keys=True, separators=(",", ":"))
    doc["content_sha256"] = hashlib.sha256(payload.encode("utf-8")).hexdigest()

    return doc


def main() -> int:
    check = "--check" in sys.argv
    stale = False

    for artifact in ARTIFACTS:
        doc = build(artifact)
        text = json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
        out = artifact["out"]

        if check:
            if not out.exists() or out.read_text(encoding="utf-8") != text:
                print(f"STALE — {out.relative_to(ROOT)} does not match the corpus")
                stale = True
            else:
                print(f"OK — {out.relative_to(ROOT)} is current")
            continue

        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
        print(
            f"wrote {out.relative_to(ROOT)} — {doc['entry_count']} entries, "
            f"sha256 {doc['content_sha256'][:12]}, "
            f"{doc['verification_summary']}"
        )

    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
